rewrite required programs section

diff --git a/find-and-scan-shell-scripts-sh b/find-and-scan-shell-scripts-sh
--- a/find-and-scan-shell-scripts-sh
+++ b/find-and-scan-shell-scripts-sh
@@ -534,23 +534,25 @@ function W_() {
 : 'Required programs'
 
 reqd_progs=(strings)
-unset b reqd_progs_exit # [Line 1] +./find-and-scan-shell-scripts-sh:302:: unset b reqd_progs_exit
+unset b reqd_progs_list reqd_progs_exit
+
 for b in "${reqd_progs[@]}"; do
   hash -r
-  if ! type -P "${b}" 2>/dev/null; then
+  
+  if ! type -P "${b}" > /dev/null 2>&1; then
+    reqd_progs_list+=("${b}")
+    
     if [[ -z "${reqd_progs_exit}" ]]; then
       reqd_progs_exit=yes
-      printf '\n\tThe following programs are required:\n'
     fi
-    printf '\t\t%s\n' "${b}"
   fi
-done
-unset b # [Line 2] +./find-and-scan-shell-scripts-sh:311:: unset b
-# ^--- added `wait -f` at line302
-if [[ "${reqd_progs_exit}" == yes ]]; then
-  echo
+done; unset b
+
+if [[ "${reqd_progs_exit}" = 'yes' ]]; then
+  printf '\n\tThe following programs are required:\n'
+  printf '\t  %s\n' "${reqd_progs_list[@]}"
   exit 1
-fi
+fi; reqd_progs reqd_progs_list reqd_progs_exit
 
 exit 101
 #_full_xtrace
