add a `command -p`, edit `mkdir`, alter comments

diff --git a/find-and-scan-shell-scripts-sh b/find-and-scan-shell-scripts-sh
--- a/find-and-scan-shell-scripts-sh
+++ b/find-and-scan-shell-scripts-sh
@@ -10,16 +10,16 @@ severity='error'
 shells='(sh|bash|dash|ksh)'
 
 # Environment variables
-PATH="$( getconf PATH ):/usr/bin:/usr/sbin:${PATH}"
+PATH="$( command -p getconf PATH ):/usr/bin:/usr/sbin:${PATH}"
 LC_ALL=C
 
 # Process lock
 lock_d=/tmp/scf.lock
 trap 'if [[ -d "$lock_d" ]] && [[ ! -L "$lock_d" ]]; then sudo rm -rf -- "$lock_d"; fi; trap - EXIT TERM INT; kill -s INT "$$"' EXIT TERM INT # on one line for cleaner xtrace output
-if mkdir -- "$lock_d"; then
-  printf '\nSuccessfully acquired lock: %s\n\n' "$lock_d" 1>&2
-else
-  printf '\n\tCannot acquire lock: exiting.\n\n' 1>&2
+if ! mkdir "$lock_d"; then
+  #printf '\nSuccessfully acquired lock: %s\n\n' "$lock_d" 1>&2
+#else
+  printf '\n\tCannot acquire process lock: <%s>.\n\tExiting.\n\n' 1>&2
   exit 2
 fi
 
@@ -43,8 +43,7 @@ export \
   file \
   first_two_chars \
   fstype_regexp \
-  i_1 \
-  i_2 \
+  i_{1..9} \
   LC_ALL \
   line_1 \
   mountpoint \
