corrected a variable namespace collision

diff --git a/find-and-scan-shell-scripts-sh b/find-and-scan-shell-scripts-sh
--- a/find-and-scan-shell-scripts-sh
+++ b/find-and-scan-shell-scripts-sh
@@ -187,8 +187,7 @@ mapfile -d '' -t    all_files_sorted < <(
 
 ###  SECTION B  ###
 # Add some brevity, and write the completed arrays to disk
-c="${#all_files_sorted[@]}"
-f="${datafile}"
+count="${#all_files_sorted[@]}"
 unset IFS
 
 # Functions for this section
@@ -199,7 +198,7 @@ _scan_local_disks(){
   for i_1 in "${!all_files_sorted[@]}"; do
     
     unset f X od_o line_1 
-    f="${all_files_sorted[${i_1}]}"
+    file="${all_files_sorted[${i_1}]}"
 
     # Bug, inordinately long interpreter paths are rare, but do occur.
     # Read from disk in binary the first two bytes of each file in 
@@ -209,26 +208,26 @@ _scan_local_disks(){
     #   Note: `od` command is POSIX compliant
     # shellcheck disable=SC2034
     builtin read -r X od_o X < <( 
-      sudo od -N2 -x "${f}" ||
+      sudo od -N2 -x "$file" ||
         _erx "${LINENO}" ) 
    
     # If 'od_o' contains some non-zero data, as it should, 
-    if [[ -z "${od_o}" ]]; then
-      _erx "${LINENO}"
+    if [[ -z "$od_o" ]]; then
+      _erx "$LINENO"
 	
     # compare the hexidecimal representations to find any crashbangs.
-    elif [[ "${od_o}" == '2123' ]]; then
+    elif [[ "$od_o" == '2123' ]]; then
       
       # Use 'read', and hope there won't be any non-printable characters.
-      IFS= builtin read -r line_1 < "${f}" ||
-          _erx "${LINENO}"
+      IFS= builtin read -r line_1 < "$file" ||
+          _erx "$LINENO"
 
       # Issue: the files with '#!comment' as the initial bytes
-      if [[ "${line_1}" =~ ^#!comment ]]; then
+      if [[ "$line_1" =~ ^'#!comment' ]]; then
         
           set -x
 
-        files_with_hashbang_comments+=( [${i_1}]="${f}" )
+        files_with_hashbang_comments+=( [${i_1}]="$file" )
         unset 'all_files_sorted[$i_1]'
         
           set -
@@ -236,29 +235,25 @@ _scan_local_disks(){
         continue
       fi
 
-      # Issue: files originating outside of rpm package manager
-      if ! rpm -qf "${f}" 2> /dev/null 1>&2; then
-        
-          set -x
+      # Issue: crashbang files which originate outside of the rpm 
+      # package manager
+      if ! rpm -qf "$file" 2> /dev/null 1>&2; then
 
-        files_from_outside_rpm+=( [${i_1}]="${f}" )
-        unset 'all_files_sorted[$i_1]'
-        
-          set -
-
-        continue
+        # double counting these scripts, both in this array as well as
+        # in 'shell_scripts' just below
+        files_from_outside_rpm+=( [${i_1}]="$file" )
       fi
 
       # Make a record of the filenames and their crashbangs in RAM.
-      shell_scripts+=( [${i_1}]="$( 
-        printf '%-50s   %% %% %% %%   %s\n' "${line_1}" "${f}" )" )
+      shell_scripts+=( [$i_1]="$( 
+        printf '%-50s   %% %% %% %%   %s\n' "$line_1" "$file" )" )
       unset 'all_files_sorted[$i_1]'
     else
-      all_other_files+=( [${i_1}]="${f}" )
+      all_other_files+=( [$i_1]="$file" )
       unset 'all_files_sorted[$i_1]'
     fi
 
-    printf '%d of %d\r' "${i_1}" "${c}"
+    printf '%d of %d\r' "$i_1" "$count"
     wait -f
   done
 }
@@ -266,33 +261,34 @@ _scan_local_disks(){
 # Open a timestamped file & append into it the list of filenames and 
 # their crashbangs. 
 _create_datafile(){
-  
     # <>
     set -x
 
   # create the original datafile
-  touch "${f}" /tmp/"${f##*/}"
+  touch "$datafile" /tmp/"${datafile##*/}"
   wait -f
-  for x in "${f}" /tmp/"${f##*/}"; do
+  for x in "$datafile" /tmp/"${datafile##*/}"; do
     if [[ -f "$x" ]] && [[ ! -L "$x" ]]; then
       mv "$x" "${x}.${RANDOM}"
     fi
   done
   wait -f
-  printf '# crunchbangs -- %s \n' "${time}" | 
-    sudo tee --output-error='exit' "${f}" /tmp/"${f##*/}" \
+  printf '# crunchbangs -- %s \n' "$time" | 
+    sudo tee --output-error='exit' "$datafile" /tmp/"${datafile##*/}" \
         > /dev/null 2>&1 ||
       _erx "${LINENO}"
   printf '%s\n' "${shell_scripts[@]}" |
-    sudo tee --append --output-error='exit' "${f}" /tmp/"${f##*/}" \
+    sudo tee --append --output-error='exit' "$datafile" \
+      /tmp/"${datafile##*/}" \
         > /dev/null 2>&1 ||
       _erx "${LINENO}"
-  _bak "${f}" /tmp/"${f##*/}"
+  _bak "$datafile" /tmp/"${datafile##*/}"
 }
 
 # if the full list exists (of files on disk which begin with crash-
 # bangs), then skip the 30-90 minute search phase.
-if [[ -f /tmp/"${f##*/}" ]] && [[ ! -L /tmp/"${f##*/}" ]]; then
+if [[ -f /tmp/"${datafile##*/}" ]] && [[ ! -L /tmp/"${datafile##*/}" ]]; 
+then
   :
 else
   _scan_local_disks
@@ -302,7 +298,7 @@ fi
   # <> ##############################################################
   _record_arrays shell_scripts files_with_hashbang_comments \
     files_from_outside_rpm all_other_files 
-  _record_vars 'B' f i_1 od_o X line_1 c 
+  _record_vars 'B' file datafile i_1 od_o X line_1 count
 
   exit 101
   set -x
@@ -324,18 +320,18 @@ ere_2='>?[[:space:]]{3,}<?/?[[:alnum:]].*>?[[:space:]]{3,}<?'
 _test_2(){
   sudo grep --extended-regexp --line-number "${ere_2}" "${1}" # ere_2
 }
-if _test_2 "${f}"; then
-  sudo sed --in-place "s=${ere_2}=    =g" "${f}" # ere_2
-  _test_2 "${f}" &&
+if _test_2 "$datafile"; then
+  sudo sed --in-place "s=${ere_2}=    =g" "$datafile" # ere_2
+  \_test_2 "$datafile" &&
     _erx "${LINENO}"
 fi
-command -p cp --archive "${f}" "${f}_extra-data-removed"
-_bak "${f}_extra-data-removed"
+command -p cp --archive "$datafile" "${datafile}_extra-data-removed"
+_bak "${datafile}_extra-data-removed"
 
   # <>
-  ls -l "${f}"*
-  wc "${f}"*
-  sudo sha256sum "${f}.bak" "${f}_extra-data-removed"
+  ls -l "${datafile}"*
+  wc "${datafile}"*
+  sudo sha256sum "${datafile}.bak" "${datafile}_extra-data-removed"
   
   exit 101
   set -x
@@ -346,8 +342,9 @@ _bak "${f}_extra-data-removed"
 # Alteration 3: Apply grep-style line numbers, ie, in-file indices. These 
 # are necessary for section 'Extra,' however, can only be applied prior 
 # to the full list having been subdivided. 
-grep --extended-regexp --line-number '.' "${f}" > "${f}_all-indexed"
-_bak "${f}_all-indexed"
+grep --extended-regexp --line-number '.' "${datafile}" > \
+  "${datafile}_all-indexed"
+_bak "${datafile}_all-indexed"
 
 
 # CENTRAL TASK, 1 OF 2: Filter the list of crashbangs with the list 
@@ -356,13 +353,13 @@ _bak "${f}_all-indexed"
 # Bug likely: ere3
 ere_3=^"[0-9]{1,7}:#! ?(/usr)?/bin/(env|${shells}?) *<?(/usr)?(/bin/)?${shells} ?>? *"
 
-grep --extended-regexp "${ere_3}" "${f}_all-indexed" > \
-  "${f}_SC-scrpts-list" # ere_3
-_bak "${f}_SC-scrpts-list"
+grep --extended-regexp "${ere_3}" "${datafile}_all-indexed" > \
+  "${datafile}_SC-scrpts-list" # ere_3
+_bak "${datafile}_SC-scrpts-list"
 
   # <>
-  ls -l "${f}"*
-  wc "${f}"*
+  ls -l "${datafile}"*
+  wc "${datafile}"*
   exit 101
   set -x
 
@@ -374,8 +371,8 @@ for i_2 in "${!shell_scripts[@]}"; do
 
   # Run `shellcheck on the script and count the number of each issue's ID.
   mapfile -t careful < <( 
-    shellcheck --severity "${severity}" "${script}" || 
-      _erx "${LINENO}" )
+    shellcheck --severity "$severity" "$script" || 
+      _erx "$LINENO" )
   mapfile -t errs < <( 
     grep --fixed-strings --invert-match 'shellcheck.net' \
         <<< "${careful[@]}" | 
@@ -383,7 +380,7 @@ for i_2 in "${!shell_scripts[@]}"; do
       sort --general-numeric-sort | 
       uniq --count |
       sed 's,^[[:space:]]*,,g' || 
-        _erx "${LINENO}" )
+        _erx "$LINENO" )
 
   # Bug: formatting
 
@@ -391,19 +388,19 @@ for i_2 in "${!shell_scripts[@]}"; do
   # prioritized work lists with indices
   if [[ -n "${errs[*]:0:1}" ]]; then 
 		
-    printf '<idx:%d>  %%  <%s>\n' "${i_2}" "${script}" >> \
-      "${f}_found_scripts_with_indices"
+    printf '<idx:%d>  %%  <%s>\n' "$i_2" "$script" >> \
+      "${datafile}_found_scripts_with_indices"
 
     for each_error in "${errs[@]}"; do
-      printf '%s %% <idx:%d>\n' "${each_error//$'\n'/}" "${i_2}" >> \
-        "${f}_found_errors_with_indices_unsorted"
+      printf '%s %% <idx:%d>\n' "${each_error//$'\n'/}" "$i_2" >> \
+        "${datafile}_found_errors_with_indices_unsorted"
     done
   fi
   unset errors script 'shell_scripts[$i_2]'
 done
 
-_bak "${f}_found_scripts_with_indices" \
-  "${f}_found_errors_with_indices_unsorted"
+_bak "${datafile}_found_scripts_with_indices" \
+  "${datafile}_found_errors_with_indices_unsorted"
 
 exit 0
 
