/tmp/tmp.QsNPYTIVTH/msg merged 'regular users only', 'sudo required' blocks

diff --git a/find-and-scan-shell-scripts-sh b/find-and-scan-shell-scripts-sh
--- a/find-and-scan-shell-scripts-sh
+++ b/find-and-scan-shell-scripts-sh
@@ -5,14 +5,17 @@
 
 # SECTION A
 
-: 'Regular users only'
+: 'Regular users only, and -sudo- required'
 
 if [[ "${UID}" == 0 ]]; then
   printf '\n\t Must be a regular user and use sudo. \n\n'
   exit 1
 else
-  sudo -v \
-    || exit 1
+  if ! sudo -v; then 
+    printf '\n\tValidation failed of user\x27s \x60sudo\x60 timestamp; '
+    printf 'exiting.\n\n'
+    exit "${LINENO}"
+  fi
 fi
 
 : 'Environment variables'
@@ -1249,14 +1252,6 @@ fn_write_arrays() {
 #  B_ "${loc_write_f_a}"
 #  : 'fn_write_vars ENDS  ' "$((--funclvl))" "${fence}"
 #}
-
-: 'Use -sudo-'
-
-if ! S_ -v; then
-  printf '\n\tValidation failed of user\x27s \x60sudo\x60 timestamp; '
-  printf 'exiting.\n\n'
-  L_
-fi
 
 #X_; :_
 
