ACL section: comments, indents, `sudo -` to top, etc

diff --git a/find-and-scan-shell-scripts-sh b/find-and-scan-shell-scripts-sh
--- a/find-and-scan-shell-scripts-sh
+++ b/find-and-scan-shell-scripts-sh
@@ -15,6 +15,13 @@ PATH="$( /usr/bin/command -p getconf PATH ):/usr/bin:/usr/sbin:${PATH}"
 LC_ALL=C.UTF-8
 LC_COLLATE=C
 
+# Use `sudo`
+if ! sudo -v; then
+  printf '\n\tValidation failed of user\x27s \x60sudo\x60 timestamp; ' 
+  printf 'exiting.\n\n' 
+  exit 1
+fi
+
 # Process lock
 random="$RANDOM"
 lock_d="${XDG_RUNTIME_DIR:-"${HOME:-/tmp}"}/.${$}.${random}.lock"
@@ -330,72 +337,62 @@ datafile="${timedir}/crunchbangs"
 #unlisted="${timedir}/unlisted"
 umask 077
 
+  set -x
 
-# reduce use of `sudo` in this script
-if ! sudo -v; then
-  printf '\n\tValidation failed of user\x27s \x60sudo\x60 timestamp; ' 
-  printf 'exiting.\n\n' 
-  exit 1
-fi
-
-if set | 
-    grep -iq fedora &&
-  grep -qE ^"wheel:x:[0-9]{2,8}:${USER}$" /etc/group; 
-then
-  sudo -v ||
-    exit 1
-  sudo visudo -cs /etc/sudoers ||
-    exit 1
-
-  # set up ACL's
+# reduce use of `sudo` in this script by setting up ACL's
   
-  # get ACL's enabled on FS
-  case "$fstype" in
-    'xfs')      :;;
-    ext[2-4])   tune2fs -l "$device" | 
-                  grep -i 'acl'
-                _erx "$LINENO" TODO;;
-    *)          _erx "$LINENO" TODO;;
-  esac
+# get ACL's enabled on FS
+case "$fstype" in
+  'xfs')      :;;
+  ext[2-4])   tune2fs -l "$device" | 
+                grep -i 'acl'
+              _erx "$LINENO" TODO;;
+  *)          _erx "$LINENO" TODO;;
+esac
   
-  # on XFS
+# on XFS
 
-    # <>
-    sudo setfacl -R -b "${mountpoint%/*}"
-    sudo setfacl -R -k "${mountpoint%/*}"
+  # <>
+  sudo setfacl -R -b "${mountpoint%/*}"
+  sudo setfacl -R -k "${mountpoint%/*}"
 
-  if [[ ! -r "$scriptdir" ]]; then
-    mapfile -d '/' -t a <<< "${mountpoint}"; 
-    a[0]='/'
-    a[-1]="${a[-1]//$'\n'}"
-    d=${#a[@]}; 
-    for ((i=0;i<d;i++)); do 
-      printf '\n\t%d\n\n' $i; 
-      c="$b"; 
-      b+="/${a[$i]}"; 
-      b="$( realpath -e "$b" )"; 
-      if [[ ! -r "$b" ]]; then 
-        printf '\n\tReadable:\t%s\n' "$c"; 
-        printf '\n\tUnreadable:\t%s\n' "$b"; 
-        sudo setfacl -R -m "$USER":r-x "$b" || 
-          break
-        sudo setfacl -R -m "$USER":rwx "$scriptdir" || 
-          break; 
-
-          # <>
-          ls "${scriptdir}"/* &&
-            echo SUDO NO LONGER NECESSARY
-
+# Nearly all of the `sudo` commands below are allowing rw access, of  
+# this script's datadir, so simply using ACL's will reduce the overuse 
+# of `sudo`. This section takes the "$mountpoint" variable, portions
+# each subdirectory name into an array index, and tests each subdi-
+# rectory from the FS root up for readability by the user running
+# this script (ie, a regular user). As the absolute path is recon-
+# structed, when a non-readable directory is found, a recursive "r-x" 
+# ACL is written, and then a recursive "rwx" is written for the 
+# "$scriptdir". 
+if [[ ! -r "$scriptdir" ]]; then
+  mapfile -d '/' -t a <<< "${mountpoint}"; 
+  a[0]='/'
+  a[-1]="${a[-1]//$'\n'}"
+  d=${#a[@]}; 
+  for ((i=0;i<d;i++)); do 
+    #printf '\n\t%d\n\n' $i; 
+    #c="$b"; 
+    b+="/${a[$i]}"; 
+    b="$( realpath -e "$b" )"; 
+    if [[ ! -r "$b" ]]; then 
+      #printf '\n\tReadable:\t%s\n' "$c"; 
+      #printf '\n\tUnreadable:\t%s\n' "$b"; 
+      sudo setfacl -R -m "$USER":r-x "$b" || 
         break
-      fi ; 
-    done; 
-  fi
+      sudo setfacl -R -m "$USER":rwx "$scriptdir" || 
+        break; 
 
+        # <>
+        ls "${scriptdir}"/* &&
+          echo SUDO NO LONGER NECESSARY
 
-  #  
+      break
+    fi ; 
+  done; 
 fi
-  exit 110
 
+  exit 110
 
 
 # test for whether the "$datadir" is writeable
